global:
  scrape_interval: 2s # Scrape frequently for snappy real-time charts in demo

scrape_configs:
  - job_name: 'reliable-job-queue'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
